font_size 20.0
cursor #d1d8f3
cursor_text_color #19120e
cursor_shape block
url_color #9faae2
open_url_with default
detect_urls yes
underline_hyperlinks hover

foreground #d1d8f3
background #19120d
background_opacity 0.4
background_blur 1

# black:
color0 #19120e
color8 #9297aa
# red:
color1 #9e919f
color9 #9e919f
# green:
color2  #eb9999
color10 #eb9999
# yellow:
color3  #f6aead
color11 #f6aead
# blue:
color4  #9faae2
color12 #9faae2
# magenta:
color5  #adb6f0
color13 #adb6f0
# cyan:
color6  #dbb8d6
color14 #dbb8d6
# white:
color7  #d1d8f3
color15 #d1d8f3
