font_size 20.0
cursor #000000
cursor_text_color #ffffff
cursor_shape block
url_color #4db8fd
pen_url_with default
detect_urls yes
underline_hyperlinks hover

foreground #000000
background #ffffff
background_opacity 0.5
background_blur 1

# black:
color0 #000000
color8 #000000
# red:
color1 #4db8fe
color9 #4db8fe
# green:
color2  #4db8fe
color10 #4db8fe
# yellow:
color3  #4db8fe
color11 #4db8fe
# blue:
color4  #4db8fe
color12 #4db8fe
# magenta:
color5  #4db8fe
color13 #4db8fe
# cyan:
color6  #4db8fe
color14 #4db8fe
# white:
color7  #000000
color15 #000000
