font_size 20.0
cursor #fdfdfd
cursor_text_color #172436
cursor_shape block
url_color #9faae2
open_url_with default
detect_urls yes
underline_hyperlinks hover

foreground #fdfdfd
background #172436
background_opacity 0.4
background_blur 1

# black:
color0 #172435
color8 #172435
# red:
color1 #6d90d1
color9 #6d90d1
# green:
color2  #9ea2e9
color10 #9ea2e9
# yellow:
color3  #d9abd8
color11 #d9abd8
# blue:
color4  #f4c1c5
color12 #f4c1c5
# magenta:
color5  #facedc
color13 #facedc
# cyan:
color6  #ffeecc
color14 #ffeecc
# white:
color7  #fdfdfd
color15 #fdfdfd

